all: TMA1Question1.exe TMA1Question2.exe TMA1Question3.exe TMA1Question4.exe TMA1Question5.exe

TMA1Question1.exe: TMA1Question1.cpp
	g++ TMA1Question1.cpp -o TMA1Question1.exe

TMA1Question2.exe: TMA1Question2.cpp
	g++ TMA1Question2.cpp -o TMA1Question2.exe

TMA1Question3.exe: TMA1Question3.cpp
	g++ TMA1Question3.cpp -o TMA1Question3.exe

TMA1Question4.exe: TMA1Question4.cpp
	g++ TMA1Question4.cpp -o TMA1Question4.exe

TMA1Question5.exe: TMA1Question5.cpp
	g++ TMA1Question5.cpp -o TMA1Question5.exe

#Remove executibles.
rmexe:
	rm TMA1Question?.exe
