all: TMA1Question1 TMA1Question2 TMA1Question3 TMA1Question4 TMA1Question5

TMA1Question1: TMA1Question1.cpp
	g++ TMA1Question1.cpp -o TMA1Question1.exe

TMA1Question2: TMA1Question2.cpp
	g++ TMA1Question2.cpp -o TMA1Question2.exe

TMA1Question3: TMA1Question3.cpp
	g++ TMA1Question3.cpp -o TMA1Question3.exe

TMA1Question4: TMA1Question4.cpp
	g++ TMA1Question4.cpp -o TMA1Question4.exe

TMA1Question5: TMA1Question5.cpp
	g++ TMA1Question5.cpp -o TMA1Question5.exe

#Remove any binaries built with Sublime text during testing. 
clean:
	rm TMA1Question?
